services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx # defines how to create the Docker image
    ports:
      - "443:443"
    volumes:
      - wf:/var/www/html
    restart: unless-stopped # container have to restart in case of a crash
    depends_on:
      - wordpress
    networks:
      - web

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wf:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb # will compose mariadb first and remove wordpress before mariadb
    networks:
      - web

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: 
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
    networks:
      - web

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wf

networks:
  web:
    driver: bridge
