services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: 
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/alexandra/data/mariadb_data